#!/bin/sh

set -e
if ! type ar 2>/dev/null >/dev/null; then
  echo I need the ar executable in my path
  exit 1
fi

if ! type tar 2>/dev/null >/dev/null; then
  echo I need the tar executable in my path
  exit 1
fi

rm -rf data
mkdir data
for i in *.ipk; do
  cd data
  rm -f *.tar.gz
  ar x ../$i
  tar zxf data.tar.gz
  cd ..
done

if [ -d data/data/data/org.woltage.irssiconnectbot/files ]; then
  cd data/data/data/org.woltage.irssiconnectbot/files
  # given an mp3 extension due to a bug in the resource compression system
  tar zcf ../../../../../../res/raw/data.tar.gz.mp3 .
else
  echo path data/data/data/org.woltage.irssiconnectbot/files not found
  exit 1
fi
